ngspice: Autospec creation for update from version 42 to version 43
Brian Taylor (15):
      Several PSPICE 9.1 evaluation digital libraries contain timing .model statements at the global level for subckts with U* instances that reference those models. By specifying "set ps_global_tmodels=1" in .spiceinit an extra pass inside u_instances() will collect those global timing models for use in subckts. Report errors detected when ngspice parses a LOGICEXP but has not added support for operator precendence. Include a hint of how to fix those errors by inserting parentheses. This error only occurs in 10 of 585 cases in the libraries. Note that inpcompat.c has been saved as a unix filetype.
      There are approx. 47 out of 1455 subckts in PSPICE 9.1 libraries which contain X* subckt calls together with zero or more U* instances. Now this type of subckt can be translated to XSPICE.
      Replace the logicexp parser with infix to postfix translation followed by evaluating the postfix. logicexp.c is now shorter and easier to understand and maintain. Also, operator precedence expression parsing conforms to the PSPICE rules. Thus, a & b | c is understood to mean (a & b) | c, for example.
      Add error detection and reporting for invalid infix expressions.
      Add check for a trailing } in a logicexp statement.
      Remove old dead code.
      Add WARNINGs when there are potential name collisions, and identify the possible name.
      The lexer incorrectly treats a single '_' '-' '/' as an identifier. The counter used for tmp__ names should be incremented after use. The infix_to_postfix converter now has more checks for invalid infix expressions in LOGICEXP constructs. Without these checks the evaluation of the generated postfix could silently create bad gates which would load but simulate incorrectly. All MicroCap and PSpice libraries and QEI.cir pass their tests.
      Return correct error statuses. Detect another illegally placed gate operator in an infix expression.
      Fix bug in the LOGICEXP scan_gates optimizer. Some gates with an inverting output were generated with bad logic which gave incorrect simulation results.
      Add variable ps_scan_gates_optimize (default 1). If < 1, then turn off the optimizations in scan_gates.
      Remove unnecessary #include.
      Go back to before previous merge.
      Fix scan_gates to consider correctly gates with an inverted output. Refactor the checks in infix_to_postfix for invalid postfix expressions.
      Cleanup gcc compiler warnings.

Giles Atkinson (13):
      A quick fix for a bug reported in the Help forum by Tom Hajjar on
      Improve scheduling of breakpoints for V-source (PULSE and PWL).
      Use all available precision when creating a "plot" command for a
      Change the code that makes variables from device/model parameters
      Use the correct type of hash table for device and model names.
      Support use of vector defaults for XSPICE vector parameters.
      Change CMPP-related struct Mif_Parse_Value to a union
      Make the 'Null_Allowed' option for XSPICE code model parameters
      Tidy d_process/ifspec.ifs so that it works after changes in
      Suppress some warnings from MSVC.
      Fix a compilation error when using compile_macos_clang.sh and update
      Fix an error in cfbe1afa21b3 that causes a crash in d_cosim.
      Prevent lines beginning '#' in .include files from being treated

Holger (1):
      Update: except for CIDER all relevant options are included

Holger Vogt (118):
      Patch for snprintf provided by Marco Atzeri
      Add d_cosim to MS project file
      Remove as it is oild and redundant
      Remove ADMS, add KLU
      Remove ADMS from build process
      Avoid memory crash when reading old VDMOS models.
      Prevent vectors carrying the E POLY source current from being disaggregated
      Patches provided by Carsten Schoenert: Misspellings, File access
      In PS compat mode we only have 2 nodes in a diode,
      Previous AM was buggy in V(I)SRC: Update to amplitude modulation
      We are developing towards ngspice-43
      Extend the error message
      Set new default values.
      Update to V/I sources, SFFM and AM
      Example for V/I sources, SFFM and AM
      If there is a successful step, but the goal is not yet reached,
      C:\Spice64 is again the default install directory for ngspice made by MSVC.
      Don't derefence Matrix->SMPkluMatrix->KLUmatrixCommon if it is NULL.
      Automatically adding diode RS only when variable 'rsdiode' is set
      Fix dd7b9ff27
      Add a transformer with parameters on the .subckt line
      compile with gcc-14 fails due to `-Werror=incompatible-pointer-types`
      F source fails when VNAM contains math symbols like '-'.
      Preliminary fix to bug report 660
      As preliminary, better not change CURRENT
      Make PSP103_nqs standard, as it is used by the Open PDK from IHP
      Don't use printf(".."), but fprintf(stdout, "..."),
      Upon a warning on a model issue, ngspice should not bail out,
      Upon error, bail out when strict_error is set.
      temporary printout of deck
      Fix a bug in 'reset', where .subckt are not transformed
      If TRACE is defined, print out everything without comment lines,
      add 'option klu' to printout
      Prevent error: implicit declaration of function ‘get_local_home’
      The values used in the foreach loop my be given by a vector
      Repeat loop requires plain number, transformed vector, or transformed variable
      Bug 664: Report an error if token in meas statement is not a vector and
      measure example with expression evaluation
      Add a evaluation function which truly removes also the
      fix a bug in the ={par({...})} function.
      Improve response to error: reporting the error when
      Bug 665: enable compiling the code models with link time optimization.
      Unify the function interface, avoid lto-type-mismatch
      Unify all spinit sources
      Add a new exported function ngSpice_nospinit() to set
      Guard reading and executing spinit by variable no_spinit.
      correct the link to the license text.
      no lower casing for file input paths
      optran 0 0 0 0 0 uic may be used to load initial conditions
      avoid crash when compiled with lto
      allow compiling with CIDER deselected
      Add environmental variable NGSPICE_OSDI_DIR. It may contain
      Stop ngspice in case of pwl errors, avoid crash.
      Replace IOP by IOPR
      while copying a deck, copy the new infos
      Add 'linesource', to contain the path/file of the origin of the line.
      Add an additional funtion parameter 'filename' to fcn inp_readall
      Do not add line number 0, but the number of the original
      Allow delay of 0, as requested by Infineon model of the 2EDNY52X
      Add the original line source information to the new line.
      Add file_name to fcn inp_read
      New parameter char *linesource for fcn insert_new_line
      Add char *lineinfo to parameters of fcn  insert_new_line
      Add linenum_orig and linesource info to newly generated
      Add linum_orig and linesource to commented out *include line
      Add (enhanced) patch by Giles Atkinson
      Add a fcn wl_delete to free the wordlist, but not its wl_word contents.
      Save the wordlist sourceinfo to the current circuit.
      Reload sourceinfo when changing the current circuit.
      Don't delete sourceinfo as it may lead to a crash upon 'quit'.
      Now standard while compiling (no need to be added to ./configure):
      Clear the variable before checking anew if it is to be set.
      Identifier 'card' may not be available or not useful when
      Save path to .include file, add it to the search paths
      Improve error message if malloc or realloc fails.
      Issue this warning only when 'set ngdebug' is given.
      Transform nested braces {{}} into {()} also in .param statements
      Add '.save nosub' to suppress storing the node vectors from inside
      Search path for .lib and .include has been enhanced to read complete
      Improve comment
      'No OP' is the more important news, update note to the user.
      Enable coupling of more than 2 inductots in a single line:
      Remove Valgrind "potentially undefined" message.
      Add ft_spiniterror, to be set during spinit processing,as
      When reading code models, allow only a single model pere command
      Error messages to stderr only.
      Enable monotonic negative growth of abscissa values.
      Bail out when the instance line is not complete.
      Add function check_for_nodes to
      Skip output lines starting with 'Operating'
      Revise commit
      Improved warning message: hint to line causing the warning.
      Send warning message to stderr, not to stdout.
      add path or filepath (without file name) to variable sourcepath,
      Plug a memory leak
      Prepare ngspice-43
      Authorship for HICUM
      Enable single terminal n devices (Verilog-A modules)
      Prevent crash upon buggy user input
      If compiling shared ngspice, don't set up a terminal.
      Remove VS compiler warning
      Repair the link to the xhtml manual
      When compiling console debug, use debug version of KLU
      Fix common typo: unkown -> unknown
      Update the Information files for ngspice-43
      Don't check for readline, if shared lib or Windows GUI is selected
      Remove
      compile cygwin for short make check, sveral options now included
      Compile scripts MINGW with options alraedy included
      Don't enable functions 'time' or 'getrusage' when OpenMP is selected
      Options are now included
      Options are now included automatically.
      Update to macOS compile scripts
      VBIC nqs
      Apple M2
      More files into distribution
      Missing \
      Update copyright info

Pat Deegan (2):
      Diode Model Parameters, Level 3, support for diode breakdown voltage synonyms, as used in sky130 PDK
      level 3 note on breakdown voltage params

dwarning (50):
      correct flicker noise term for mos1 and mos2 - bug #656
      correct bartlett/triangle fft window formulae
      window weightings between 0 and 1 for fft vector function and command
      fft window functions back to correct scaling - no need need for post scaling step
      partially revert commit aafd7bbb: spec triangular window
      rm obsolete order for spec blackman window
      two corrections in Ycor and NF formulae
      formatting mos1...3 noise code
      selectable flicker noise models for mos1...3
      mos1...3: formatting and white spaces
      mos3mask: change unusual structure name
      mos1...3: add nlev=3 mode channel thermal noise
      mos1...3: Beta in noise w/o channel length modulation
      rm confusing comments and formatting
      too soon return - break is correct
      format
      bjt, dio, jfet, res: use device temperature for noise analysis too
      mos1...3: use device temperature for noise analysis too
      vbic: use device temperature for noise analysis too
      hicum2: use device temperature for noise analysis too
      prevent clang error
      no use for grouping in cx_fft and cx_ifft
      introduce diode breakdown voltage parameter alias vb
      introduce jfet gate-drain and gate-source junction emission coefficient
      only access to CKTkluMODE if KLU configured
      use only magnitudes in ac noise analysis even if openvaf compiled models deliver negative noise contributions
      format
      use limexp to prevent NaN with extreme exponents
      Support op-pt values by Geoffrey Coram
      vbic: rm obsolete regression test
      change CR/LF to LF
      diode: add model parameter xw for mask and etching effect (level=3)
      diode: add alternative bangap calculation for tlev=2
      diode: add saturation current temperature model tlev=2
      diode: no need for vte recalculation, rhs not changed
      mos1...3: logical error-prevent garbage for nlev=3
      mos1...3: set channel thermal noise to 0 in subthreshold range for nlev=3
      revert commit ea4c438 and db85dead by removing VJ and M limiting
      vbic: add resistive part into acload
      vbic: first add reactive part into acload
      vbic: more adding reactive part into acload
      vbic: complete reactive part into acload
      vbic: save Vrth into state vector
      vbic: init of thermal capacitances
      first attempt to include NQS effect
      more complete vbic dc/tran nqs effect
      complete vbic nqs effect implementation
      repair missing parenthesis
      init of potential uninitialized variables
      diode: init of potential uninitialized variable

Ngspice-43, July 14th, 2024
============
- New features:
    + Compile on Apple M2
    + Update to VBIC model: Enable self-heating in AC sim, enable nqs.
    + Enable single terminal n devices (Verilog-A modules)
    + Add path or filepath (without file name) to variable sourcepath,
      when calling command 'source'
    + B source pwl, enable monotonic negative growth of abscissa values.
    + Enable coupling of more than 2 inductots in a single line:
      K1 L1 L2 L3 L4 L5 0.99
    + Enable reading library search paths from env. variables like
      .lib "$ENVS1/$ENVS2/libraries/sky130_fd_pr/latest/models/sky130.lib.spice" tt
    + Add '.save nosub' to suppress storing the node vectors from inside
      of subcircuits.

(NEWS truncated at 15 lines)